JsonObject reports multiple mismatches
spotify/java-hamcrest pull request #5
Opened 2017-01-10 16:12 UTC by eshrubs

In the current implementation only the first mismatch will be detected. This is
not desirable as one `assertThat` should show all mistmatches, as is done with 
similar hamcrest matches like `containsInAnyOrder`

2017-01-16 17:26 UTC, dflemstr requested changes

2017-01-16 17:26 UTC, dflemstr commented on jackson/src/main/java/com/spotify/hamcrest/jackson/IsJsonObject.java
> +
?

2017-01-16 17:26 UTC, dflemstr commented on jackson/src/test/java/com/spotify/hamcrest/jackson/IsJsonObjectTest.java
> +            + "  ...\n"
Would prefer to leave this indentation as is :-)

2017-01-16 17:26 UTC, dflemstr commented on jackson/src/test/java/com/spotify/hamcrest/jackson/IsJsonObjectTest.java
> +            + "  ...\n"
Nice, wanted this for a long time!

2017-02-07 14:49 UTC, eshrubs commented
@dflemstr Go nuts!

2017-02-07 14:59 UTC, eshrubs commented
@dflemstr Go nuts!

2017-02-13 15:56 UTC, eshrubs commented
@davidxia @mattnworb Poke!

2017-02-13 16:08 UTC, mattnworb approved these changes
Neat, I didn't realize standard matchers like `containsInAnyOrder` did this. I've definitely written a bunch of one off matchers that only report the first mismatch. LGTM!

2017-02-13 22:15 UTC, merged